In [1]:
import pandas as pd
import requests
from yfinance import Ticker, Tickers
pd.set_option('display.max_columns', None)

#### Getting the ticker data from `sec.gov`

In [70]:
ticker_url = "https://www.sec.gov/files/company_tickers.json"
headers = {'User-Agent': "email@address.com"}

# get all companies data
companyTickers = requests.get(
        url=ticker_url,
        headers=headers
    )
data = [v for k,v in companyTickers.json().items()]
df = pd.DataFrame(data)

def standardize_cik(cik):
    """Padding `0` to make it 10 digits and then adding `CIK` string at start""" 
    return 'CIK' + str(cik).zfill(10)
    

df['cik_str'] = df['cik_str'].apply(standardize_cik)
df

            cik_str ticker                        title
0     CIK0001045810   NVDA                  NVIDIA CORP
1     CIK0000320193   AAPL                   Apple Inc.
2     CIK0001652044  GOOGL                Alphabet Inc.
3     CIK0000789019   MSFT               MICROSOFT CORP
4     CIK0001018724   AMZN               AMAZON COM INC
...             ...    ...                          ...
9299  CIK0000791908  XOMAO            XOMA Royalty Corp
9300  CIK0000791908  XOMAP            XOMA Royalty Corp
9301  CIK0002101470  WLCOU                Wilco 63 Corp
9302  CIK0002100125  CAQUU  Cambridge Acquisition Corp.
9303  CIK0002100125  CAQUW  Cambridge Acquisition Corp.

[9304 rows x 3 columns]

#### Getting ohlcv data for company tickers

In [79]:
# Getting all tickers in a list
companyTickersList = list(df.ticker)

# Fetching the market data for tickers
data = Tickers(companyTickersList[4176:4276])
df1 = data.history(interval='1m', start='2026-07-05', auto_adjust=False)
df1

[********              16%                       ]  16 of 100 completed$GSHR: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:24-04:00)
[****************      33%                       ]  33 of 100 completed$MAMK: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:25-04:00)
[**********************85%****************       ]  85 of 100 completed$MAGH: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:26-04:00)
[*********************100%***********************]  100 of 100 completed

3 Failed downloads:
['GSHR']: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:24-04:00)
['MAMK']: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:25-04:00)
['MAGH']: possibly delisted; no price data found  (1m 2026-07-05 -> 2026-07-12 05:53:26-04:00)

Price                      Adj Close                                        \
Ticker                          AIFU   AIRO       ALOT   ALTG   ANIK  AOMR
Datetime
2026-07-06 09:30:00-04:00        NaN  7.860  28.525000  6.210    NaN  9.03
2026-07-06 09:31:00-04:00        NaN  7.830        NaN  6.070    NaN   NaN
2026-07-06 09:32:00-04:00        NaN  7.880  28.530001  6.080    NaN   NaN
2026-07-06 09:33:00-04:00        NaN    NaN        NaN    NaN    NaN   NaN
2026-07-06 09:34:00-04:00        NaN  7.775        NaN    NaN    NaN   NaN
...                              ...    ...        ...    ...    ...   ...
2026-07-10 15:55:00-04:00        NaN  6.305  28.510000  6.590    NaN  9.04
2026-07-10 15:56:00-04:00        NaN  6.305        NaN  6.590    NaN   NaN
2026-07-10 15:57:00-04:00  36.990002  6.300  28.510000  6.585  15.59  9.06
2026-07-10 15:58:00-04:00        NaN  6.300  28.510000  6.580    NaN  9.03
2026-07-10 15:59:00-04:00        NaN  6.275  28.510000  6.620  15.59  9.03

Price                                                                        \
Ticker                      ASUR       BDSX BGIN BIII  BLRK BXSY  CAMP CCAQ
Datetime
2026-07-06 09:30:00-04:00  8.220  21.809999  NaN  NaN  9.99  NaN  4.42  NaN
2026-07-06 09:31:00-04:00  8.050        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:32:00-04:00  8.275        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:33:00-04:00    NaN        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:34:00-04:00    NaN        NaN  NaN  NaN   NaN  NaN   NaN  NaN
...                          ...        ...  ...  ...   ...  ...   ...  ...
2026-07-10 15:55:00-04:00  7.810        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:56:00-04:00  7.850        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:57:00-04:00    NaN  21.530001  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:58:00-04:00  7.830  21.260000  NaN  NaN   NaN  NaN  4.35  NaN
2026-07-10 15:59:00-04:00  7.820  21.309999  NaN  NaN   NaN  NaN   NaN  NaN

Price                                                                     \
Ticker                          CMTV CRAC    CRNT CTAA       CZWI   DWSN
Datetime
2026-07-06 09:30:00-04:00  39.500000  NaN  2.4100  NaN  23.754999  5.890
2026-07-06 09:31:00-04:00  38.000000  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:32:00-04:00  40.200001  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:33:00-04:00  39.500000  NaN  2.4310  NaN        NaN    NaN
2026-07-06 09:34:00-04:00        NaN  NaN  2.4399  NaN        NaN  5.890
...                              ...  ...     ...  ...        ...    ...
2026-07-10 15:55:00-04:00        NaN  NaN     NaN  NaN  23.065001  7.525
2026-07-10 15:56:00-04:00        NaN  NaN  2.3450  NaN  23.059999  7.470
2026-07-10 15:57:00-04:00        NaN  NaN  2.3450  NaN  23.049999  7.540
2026-07-10 15:58:00-04:00  38.639999  NaN  2.3500  NaN        NaN  7.570
2026-07-10 15:59:00-04:00        NaN  NaN  2.3550  NaN  23.070000  7.590

Price                                                                     \
Ticker                          EFSI   EGG EGHA   EVTL       FCAP     FF
Datetime
2026-07-06 09:30:00-04:00  41.904999  7.19  NaN  1.940  65.750000  4.720
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  1.935        NaN  4.715
2026-07-06 09:33:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:34:00-04:00        NaN   NaN  NaN  1.920        NaN  4.715
...                              ...   ...  ...    ...        ...    ...
2026-07-10 15:55:00-04:00  40.560001   NaN  NaN  1.665        NaN  4.665
2026-07-10 15:56:00-04:00        NaN   NaN  NaN  1.670        NaN  4.665
2026-07-10 15:57:00-04:00  40.560001   NaN  NaN  1.670        NaN  4.660
2026-07-10 15:58:00-04:00  40.509998   NaN  NaN  1.665        NaN  4.660
2026-07-10 15:59:00-04:00  40.509998   NaN  NaN  1.660  61.950001  4.640

Price                                                                       \
Ticker                      FJET        FOA FOCL FOTB    GCTS GDEV    GENC
Datetime
2026-07-06 09:30:00-04:00  5.030  27.250000  NaN  NaN  2.6865  NaN     NaN
2026-07-06 09:31:00-04:00  4.950        NaN  NaN  NaN  2.6700  NaN     NaN
2026-07-06 09:32:00-04:00  4.930        NaN  NaN  NaN     NaN  NaN     NaN
2026-07-06 09:33:00-04:00  4.930        NaN  NaN  NaN  2.6550  NaN     NaN
2026-07-06 09:34:00-04:00  4.945        NaN  NaN  NaN  2.6551  NaN     NaN
...                          ...        ...  ...  ...     ...  ...     ...
2026-07-10 15:55:00-04:00  4.425  25.530001  NaN  NaN  2.4503  NaN     NaN
2026-07-10 15:56:00-04:00  4.450        NaN  NaN  NaN  2.4650  NaN     NaN
2026-07-10 15:57:00-04:00  4.430  25.490000  NaN  NaN  2.4650  NaN  15.485
2026-07-10 15:58:00-04:00  4.425  25.625000  NaN  NaN  2.4650  NaN  15.480
2026-07-10 15:59:00-04:00  4.440  25.830000  NaN  NaN  2.4600  NaN  15.535

Price                                                                         \
Ticker                      GLATF    GORO GSHR    GTE HAVA ICTSF IDAC    IDE
Datetime
2026-07-06 09:30:00-04:00  0.4723  1.2850  NaN  5.910  NaN   NaN  NaN  13.82
2026-07-06 09:31:00-04:00     NaN  1.2850  NaN  5.915  NaN   NaN  NaN    NaN
2026-07-06 09:32:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN    NaN
2026-07-06 09:33:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN  13.83
2026-07-06 09:34:00-04:00     NaN  1.2900  NaN    NaN  NaN   NaN  NaN    NaN
...                           ...     ...  ...    ...  ...   ...  ...    ...
2026-07-10 15:55:00-04:00     NaN  1.2850  NaN  6.240  NaN   NaN  NaN    NaN
2026-07-10 15:56:00-04:00     NaN  1.2800  NaN  6.245  NaN   NaN  NaN    NaN
2026-07-10 15:57:00-04:00     NaN  1.2899  NaN  6.260  NaN   NaN  NaN    NaN
2026-07-10 15:58:00-04:00     NaN  1.2800  NaN  6.260  NaN   NaN  NaN    NaN
2026-07-10 15:59:00-04:00  0.4306  1.2850  NaN  6.265  NaN   NaN  NaN  13.56

Price                                                                     \
Ticker                        IIF    IMMR    IMPP INBK IRAB    JRVR KISB
Datetime
2026-07-06 09:30:00-04:00  22.980  6.7175     NaN  NaN  NaN     NaN  NaN
2026-07-06 09:31:00-04:00     NaN  6.7000     NaN  NaN  NaN  4.4409  NaN
2026-07-06 09:32:00-04:00     NaN  6.6900  4.6750  NaN  NaN  4.4999  NaN
2026-07-06 09:33:00-04:00     NaN     NaN  4.6838  NaN  NaN     NaN  NaN
2026-07-06 09:34:00-04:00     NaN     NaN  4.6800  NaN  NaN     NaN  NaN
...                           ...     ...     ...  ...  ...     ...  ...
2026-07-10 15:55:00-04:00     NaN  6.7600     NaN  NaN  NaN  4.5650  NaN
2026-07-10 15:56:00-04:00     NaN  6.7550  4.9750  NaN  NaN  4.5600  NaN
2026-07-10 15:57:00-04:00     NaN  6.7550  4.9750  NaN  NaN  4.5650  NaN
2026-07-10 15:58:00-04:00     NaN  6.7550  4.9900  NaN  NaN  4.5650  NaN
2026-07-10 15:59:00-04:00  22.975  6.7550  5.0000  NaN  NaN  4.5600  NaN

Price                                                                          \
Ticker                      KRMD   KRRO   LFMD    LIEN  LMED MAGH MAMK    MFM
Datetime
2026-07-06 09:30:00-04:00  4.480  13.93  4.905  9.9200  3.87  NaN  NaN  5.610
2026-07-06 09:31:00-04:00    NaN  13.95  4.910     NaN   NaN  NaN  NaN    NaN
2026-07-06 09:32:00-04:00    NaN    NaN  4.968     NaN   NaN  NaN  NaN  5.605
2026-07-06 09:33:00-04:00    NaN    NaN  4.970  9.9600   NaN  NaN  NaN    NaN
2026-07-06 09:34:00-04:00    NaN    NaN    NaN     NaN   NaN  NaN  NaN  5.605
...                          ...    ...    ...     ...   ...  ...  ...    ...
2026-07-10 15:55:00-04:00  4.285  14.49  4.635  9.8150   NaN  NaN  NaN  5.530
2026-07-10 15:56:00-04:00    NaN  14.48  4.620  9.8150   NaN  NaN  NaN  5.530
2026-07-10 15:57:00-04:00  4.280  14.45  4.615  9.8275   NaN  NaN  NaN  5.535
2026-07-10 15:58:00-04:00  4.285  14.50  4.630     NaN   NaN  NaN  NaN  5.535
2026-07-10 15:59:00-04:00  4.280  14.55  4.640  9.8225   NaN  NaN  NaN  5.535

Price                                                                     \
Ticker                     MNTK     NBP   NERV       NKSH    NPV    NUCL
Datetime
2026-07-06 09:30:00-04:00   NaN  2.2272  5.070        NaN  11.56  8.8300
2026-07-06 09:31:00-04:00   NaN  2.1800    NaN  36.009998    NaN  8.7700
2026-07-06 09:32:00-04:00   NaN  2.1400  5.100        NaN    NaN     NaN
2026-07-06 09:33:00-04:00   NaN  2.1000    NaN        NaN    NaN     NaN
2026-07-06 09:34:00-04:00   NaN  2.0809    NaN        NaN    NaN  8.6100
...                         ...     ...    ...        ...    ...     ...
2026-07-10 15:55:00-04:00   NaN  1.9000  4.800  35.970001    NaN  6.8459
2026-07-10 15:56:00-04:00   NaN  1.8950  4.796        NaN    NaN     NaN
2026-07-10 15:57:00-04:00  1.62  1.8950  4.750        NaN  11.38     NaN
2026-07-10 15:58:00-04:00  1.62  1.8950  4.730        NaN  11.41  6.8350
2026-07-10 15:59:00-04:00  1.61  1.8950  4.710  35.810001  11.41  6.8500

Price                                                                \
Ticker                      ONCH   OPBK PALO PEBK       PMTS   PNNT
Datetime
2026-07-06 09:30:00-04:00  10.35  15.23  9.9  NaN  20.379999  3.500
2026-07-06 09:31:00-04:00    NaN  15.22  NaN  NaN        NaN  3.479
2026-07-06 09:32:00-04:00    NaN    NaN  NaN  NaN  20.504999  3.520
2026-07-06 09:33:00-04:00    NaN    NaN  NaN  NaN        NaN  3.510
2026-07-06 09:34:00-04:00    NaN    NaN  NaN  NaN        NaN  3.530
...                          ...    ...  ...  ...        ...    ...
2026-07-10 15:55:00-04:00    NaN  14.87  NaN  NaN        NaN  3.460
2026-07-10 15:56:00-04:00    NaN  14.86  NaN  NaN        NaN  3.465
2026-07-10 15:57:00-04:00    NaN    NaN  NaN  NaN        NaN  3.450
2026-07-10 15:58:00-04:00    NaN  14.86  NaN  NaN  19.495001  3.450
2026-07-10 15:59:00-04:00    NaN  14.88  NaN  NaN  19.495001  3.445

Price                                                                         \
Ticker                          PPIH PSRHF PTAC QNBC     QSI    QTTB    REFI
Datetime
2026-07-06 09:30:00-04:00  25.510000  1.18  NaN  NaN  0.9300  13.150  10.665
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  NaN  0.9287  13.135     NaN
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  NaN  0.9299  13.135  10.670
2026-07-06 09:33:00-04:00  26.270000   NaN  NaN  NaN  0.9299     NaN  10.670
2026-07-06 09:34:00-04:00        NaN  1.15  NaN  NaN  0.9301  13.345  10.670
...                              ...   ...  ...  ...     ...     ...     ...
2026-07-10 15:55:00-04:00  25.190001   NaN  NaN  NaN  0.8904  11.365  10.815
2026-07-10 15:56:00-04:00  25.125000   NaN  NaN  NaN  0.8878  11.310     NaN
2026-07-10 15:57:00-04:00  25.180000   NaN  NaN  NaN  0.8840  11.250  10.820
2026-07-10 15:58:00-04:00        NaN  1.10  NaN  NaN  0.8833  11.270  10.815
2026-07-10 15:59:00-04:00  25.070000   NaN  NaN  NaN  0.8827  11.200  10.820

Price                                                                         \
Ticker                       RNA   RWAY   RXST  SABA    SIDU    SITC    SLNH
Datetime
2026-07-06 09:30:00-04:00  13.60  5.580  5.530  8.30  2.6650  4.5250  1.2250
2026-07-06 09:31:00-04:00    NaN  5.610  5.575   NaN  2.6501  4.5018  1.2250
2026-07-06 09:32:00-04:00    NaN    NaN  5.586   NaN  2.6450  4.4800  1.2499
2026-07-06 09:33:00-04:00    NaN  5.610  5.615   NaN  2.6640  4.4750  1.2450
2026-07-06 09:34:00-04:00    NaN  5.615  5.580   NaN  2.6000  4.4800  1.2500
...                          ...    ...    ...   ...     ...     ...     ...
2026-07-10 15:55:00-04:00    NaN  5.300  4.970  8.18  2.1250  4.2850  1.2650
2026-07-10 15:56:00-04:00  12.38  5.305  4.965  8.18  2.1400  4.2850  1.2600
2026-07-10 15:57:00-04:00  12.46  5.310  4.965   NaN  2.1450  4.2850  1.2650
2026-07-10 15:58:00-04:00  12.45  5.305  4.955  8.18  2.1450  4.2850  1.2600
2026-07-10 15:59:00-04:00  12.49  5.313  4.950  8.18  2.1601  4.2950  1.2670

Price                                                                          \
Ticker                      SMHI       SMTI    SND   SPMC     SPOK       STRS
Datetime
2026-07-06 09:30:00-04:00  7.615  24.549999  4.720  10.15  10.5300  28.184999
2026-07-06 09:31:00-04:00    NaN        NaN  4.680    NaN  10.5800        NaN
2026-07-06 09:32:00-04:00    NaN        NaN    NaN    NaN      NaN        NaN
2026-07-06 09:33:00-04:00    NaN        NaN    NaN    NaN  10.6188  28.184999
2026-07-06 09:34:00-04:00    NaN        NaN    NaN    NaN      NaN        NaN
...                          ...        ...    ...    ...      ...        ...
2026-07-10 15:55:00-04:00  7.810        NaN  4.810    NaN  10.4150  26.010000
2026-07-10 15:56:00-04:00    NaN  23.990000  4.805    NaN  10.4200  26.129999
2026-07-10 15:57:00-04:00    NaN  23.879999  4.805    NaN  10.4150  26.049999
2026-07-10 15:58:00-04:00  7.810  23.860001    NaN    NaN  10.3999  26.100000
2026-07-10 15:59:00-04:00  7.800  23.670000  4.805    NaN  10.4050  26.080000

Price                                                                 \
Ticker                    SUGRF SVCC   TDAC TETOF TGMPF    TSI TSNDF
Datetime
2026-07-06 09:30:00-04:00   NaN  NaN  10.72   NaN   NaN  4.490   NaN
2026-07-06 09:31:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:32:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:33:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:34:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
...                         ...  ...    ...   ...   ...    ...   ...
2026-07-10 15:55:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:56:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:57:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:58:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475  0.57
2026-07-10 15:59:00-04:00   NaN  NaN    NaN   NaN   NaN  4.470  0.57

Price                                                                Close  \
Ticker                          UTMD     VLN   VYGR   WALD WEWA       AIFU
Datetime
2026-07-06 09:30:00-04:00        NaN  2.1450  3.790  1.680  NaN        NaN
2026-07-06 09:31:00-04:00        NaN  2.1469  3.805  1.690  NaN        NaN
2026-07-06 09:32:00-04:00        NaN  2.1499  3.805    NaN  NaN        NaN
2026-07-06 09:33:00-04:00        NaN  2.1201  3.811    NaN  NaN        NaN
2026-07-06 09:34:00-04:00        NaN  2.1400  3.806    NaN  NaN        NaN
...                              ...     ...    ...    ...  ...        ...
2026-07-10 15:55:00-04:00        NaN  2.0650  3.455  1.735  NaN        NaN
2026-07-10 15:56:00-04:00        NaN  2.0650  3.455    NaN  NaN        NaN
2026-07-10 15:57:00-04:00        NaN  2.0650  3.450  1.730  NaN  36.990002
2026-07-10 15:58:00-04:00        NaN  2.0650  3.453  1.730  NaN        NaN
2026-07-10 15:59:00-04:00  67.889999  2.0750  3.445  1.745  NaN        NaN

Price                                                                   \
Ticker                      AIRO       ALOT   ALTG   ANIK  AOMR   ASUR
Datetime
2026-07-06 09:30:00-04:00  7.860  28.525000  6.210    NaN  9.03  8.220
2026-07-06 09:31:00-04:00  7.830        NaN  6.070    NaN   NaN  8.050
2026-07-06 09:32:00-04:00  7.880  28.530001  6.080    NaN   NaN  8.275
2026-07-06 09:33:00-04:00    NaN        NaN    NaN    NaN   NaN    NaN
2026-07-06 09:34:00-04:00  7.775        NaN    NaN    NaN   NaN    NaN
...                          ...        ...    ...    ...   ...    ...
2026-07-10 15:55:00-04:00  6.305  28.510000  6.590    NaN  9.04  7.810
2026-07-10 15:56:00-04:00  6.305        NaN  6.590    NaN   NaN  7.850
2026-07-10 15:57:00-04:00  6.300  28.510000  6.585  15.59  9.06    NaN
2026-07-10 15:58:00-04:00  6.300  28.510000  6.580    NaN  9.03  7.830
2026-07-10 15:59:00-04:00  6.275  28.510000  6.620  15.59  9.03  7.820

Price                                                                 \
Ticker                          BDSX BGIN BIII  BLRK BXSY  CAMP CCAQ
Datetime
2026-07-06 09:30:00-04:00  21.809999  NaN  NaN  9.99  NaN  4.42  NaN
2026-07-06 09:31:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:32:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:33:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:34:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
...                              ...  ...  ...   ...  ...   ...  ...
2026-07-10 15:55:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:56:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:57:00-04:00  21.530001  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:58:00-04:00  21.260000  NaN  NaN   NaN  NaN  4.35  NaN
2026-07-10 15:59:00-04:00  21.309999  NaN  NaN   NaN  NaN   NaN  NaN

Price                                                                     \
Ticker                          CMTV CRAC    CRNT CTAA       CZWI   DWSN
Datetime
2026-07-06 09:30:00-04:00  39.500000  NaN  2.4100  NaN  23.754999  5.890
2026-07-06 09:31:00-04:00  38.000000  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:32:00-04:00  40.200001  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:33:00-04:00  39.500000  NaN  2.4310  NaN        NaN    NaN
2026-07-06 09:34:00-04:00        NaN  NaN  2.4399  NaN        NaN  5.890
...                              ...  ...     ...  ...        ...    ...
2026-07-10 15:55:00-04:00        NaN  NaN     NaN  NaN  23.065001  7.525
2026-07-10 15:56:00-04:00        NaN  NaN  2.3450  NaN  23.059999  7.470
2026-07-10 15:57:00-04:00        NaN  NaN  2.3450  NaN  23.049999  7.540
2026-07-10 15:58:00-04:00  38.639999  NaN  2.3500  NaN        NaN  7.570
2026-07-10 15:59:00-04:00        NaN  NaN  2.3550  NaN  23.070000  7.590

Price                                                                     \
Ticker                          EFSI   EGG EGHA   EVTL       FCAP     FF
Datetime
2026-07-06 09:30:00-04:00  41.904999  7.19  NaN  1.940  65.750000  4.720
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  1.935        NaN  4.715
2026-07-06 09:33:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:34:00-04:00        NaN   NaN  NaN  1.920        NaN  4.715
...                              ...   ...  ...    ...        ...    ...
2026-07-10 15:55:00-04:00  40.560001   NaN  NaN  1.665        NaN  4.665
2026-07-10 15:56:00-04:00        NaN   NaN  NaN  1.670        NaN  4.665
2026-07-10 15:57:00-04:00  40.560001   NaN  NaN  1.670        NaN  4.660
2026-07-10 15:58:00-04:00  40.509998   NaN  NaN  1.665        NaN  4.660
2026-07-10 15:59:00-04:00  40.509998   NaN  NaN  1.660  61.950001  4.640

Price                                                                       \
Ticker                      FJET        FOA FOCL FOTB    GCTS GDEV    GENC
Datetime
2026-07-06 09:30:00-04:00  5.030  27.250000  NaN  NaN  2.6865  NaN     NaN
2026-07-06 09:31:00-04:00  4.950        NaN  NaN  NaN  2.6700  NaN     NaN
2026-07-06 09:32:00-04:00  4.930        NaN  NaN  NaN     NaN  NaN     NaN
2026-07-06 09:33:00-04:00  4.930        NaN  NaN  NaN  2.6550  NaN     NaN
2026-07-06 09:34:00-04:00  4.945        NaN  NaN  NaN  2.6551  NaN     NaN
...                          ...        ...  ...  ...     ...  ...     ...
2026-07-10 15:55:00-04:00  4.425  25.530001  NaN  NaN  2.4503  NaN     NaN
2026-07-10 15:56:00-04:00  4.450        NaN  NaN  NaN  2.4650  NaN     NaN
2026-07-10 15:57:00-04:00  4.430  25.490000  NaN  NaN  2.4650  NaN  15.485
2026-07-10 15:58:00-04:00  4.425  25.625000  NaN  NaN  2.4650  NaN  15.480
2026-07-10 15:59:00-04:00  4.440  25.830000  NaN  NaN  2.4600  NaN  15.535

Price                                                                         \
Ticker                      GLATF    GORO GSHR    GTE HAVA ICTSF IDAC    IDE
Datetime
2026-07-06 09:30:00-04:00  0.4723  1.2850  NaN  5.910  NaN   NaN  NaN  13.82
2026-07-06 09:31:00-04:00     NaN  1.2850  NaN  5.915  NaN   NaN  NaN    NaN
2026-07-06 09:32:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN    NaN
2026-07-06 09:33:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN  13.83

In [80]:
df1

Price                      Adj Close                                        \
Ticker                          AIFU   AIRO       ALOT   ALTG   ANIK  AOMR
Datetime
2026-07-06 09:30:00-04:00        NaN  7.860  28.525000  6.210    NaN  9.03
2026-07-06 09:31:00-04:00        NaN  7.830        NaN  6.070    NaN   NaN
2026-07-06 09:32:00-04:00        NaN  7.880  28.530001  6.080    NaN   NaN
2026-07-06 09:33:00-04:00        NaN    NaN        NaN    NaN    NaN   NaN
2026-07-06 09:34:00-04:00        NaN  7.775        NaN    NaN    NaN   NaN
...                              ...    ...        ...    ...    ...   ...
2026-07-10 15:55:00-04:00        NaN  6.305  28.510000  6.590    NaN  9.04
2026-07-10 15:56:00-04:00        NaN  6.305        NaN  6.590    NaN   NaN
2026-07-10 15:57:00-04:00  36.990002  6.300  28.510000  6.585  15.59  9.06
2026-07-10 15:58:00-04:00        NaN  6.300  28.510000  6.580    NaN  9.03
2026-07-10 15:59:00-04:00        NaN  6.275  28.510000  6.620  15.59  9.03

Price                                                                        \
Ticker                      ASUR       BDSX BGIN BIII  BLRK BXSY  CAMP CCAQ
Datetime
2026-07-06 09:30:00-04:00  8.220  21.809999  NaN  NaN  9.99  NaN  4.42  NaN
2026-07-06 09:31:00-04:00  8.050        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:32:00-04:00  8.275        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:33:00-04:00    NaN        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:34:00-04:00    NaN        NaN  NaN  NaN   NaN  NaN   NaN  NaN
...                          ...        ...  ...  ...   ...  ...   ...  ...
2026-07-10 15:55:00-04:00  7.810        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:56:00-04:00  7.850        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:57:00-04:00    NaN  21.530001  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:58:00-04:00  7.830  21.260000  NaN  NaN   NaN  NaN  4.35  NaN
2026-07-10 15:59:00-04:00  7.820  21.309999  NaN  NaN   NaN  NaN   NaN  NaN

Price                                                                     \
Ticker                          CMTV CRAC    CRNT CTAA       CZWI   DWSN
Datetime
2026-07-06 09:30:00-04:00  39.500000  NaN  2.4100  NaN  23.754999  5.890
2026-07-06 09:31:00-04:00  38.000000  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:32:00-04:00  40.200001  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:33:00-04:00  39.500000  NaN  2.4310  NaN        NaN    NaN
2026-07-06 09:34:00-04:00        NaN  NaN  2.4399  NaN        NaN  5.890
...                              ...  ...     ...  ...        ...    ...
2026-07-10 15:55:00-04:00        NaN  NaN     NaN  NaN  23.065001  7.525
2026-07-10 15:56:00-04:00        NaN  NaN  2.3450  NaN  23.059999  7.470
2026-07-10 15:57:00-04:00        NaN  NaN  2.3450  NaN  23.049999  7.540
2026-07-10 15:58:00-04:00  38.639999  NaN  2.3500  NaN        NaN  7.570
2026-07-10 15:59:00-04:00        NaN  NaN  2.3550  NaN  23.070000  7.590

Price                                                                     \
Ticker                          EFSI   EGG EGHA   EVTL       FCAP     FF
Datetime
2026-07-06 09:30:00-04:00  41.904999  7.19  NaN  1.940  65.750000  4.720
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  1.935        NaN  4.715
2026-07-06 09:33:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:34:00-04:00        NaN   NaN  NaN  1.920        NaN  4.715
...                              ...   ...  ...    ...        ...    ...
2026-07-10 15:55:00-04:00  40.560001   NaN  NaN  1.665        NaN  4.665
2026-07-10 15:56:00-04:00        NaN   NaN  NaN  1.670        NaN  4.665
2026-07-10 15:57:00-04:00  40.560001   NaN  NaN  1.670        NaN  4.660
2026-07-10 15:58:00-04:00  40.509998   NaN  NaN  1.665        NaN  4.660
2026-07-10 15:59:00-04:00  40.509998   NaN  NaN  1.660  61.950001  4.640

Price                                                                       \
Ticker                      FJET        FOA FOCL FOTB    GCTS GDEV    GENC
Datetime
2026-07-06 09:30:00-04:00  5.030  27.250000  NaN  NaN  2.6865  NaN     NaN
2026-07-06 09:31:00-04:00  4.950        NaN  NaN  NaN  2.6700  NaN     NaN
2026-07-06 09:32:00-04:00  4.930        NaN  NaN  NaN     NaN  NaN     NaN
2026-07-06 09:33:00-04:00  4.930        NaN  NaN  NaN  2.6550  NaN     NaN
2026-07-06 09:34:00-04:00  4.945        NaN  NaN  NaN  2.6551  NaN     NaN
...                          ...        ...  ...  ...     ...  ...     ...
2026-07-10 15:55:00-04:00  4.425  25.530001  NaN  NaN  2.4503  NaN     NaN
2026-07-10 15:56:00-04:00  4.450        NaN  NaN  NaN  2.4650  NaN     NaN
2026-07-10 15:57:00-04:00  4.430  25.490000  NaN  NaN  2.4650  NaN  15.485
2026-07-10 15:58:00-04:00  4.425  25.625000  NaN  NaN  2.4650  NaN  15.480
2026-07-10 15:59:00-04:00  4.440  25.830000  NaN  NaN  2.4600  NaN  15.535

Price                                                                         \
Ticker                      GLATF    GORO GSHR    GTE HAVA ICTSF IDAC    IDE
Datetime
2026-07-06 09:30:00-04:00  0.4723  1.2850  NaN  5.910  NaN   NaN  NaN  13.82
2026-07-06 09:31:00-04:00     NaN  1.2850  NaN  5.915  NaN   NaN  NaN    NaN
2026-07-06 09:32:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN    NaN
2026-07-06 09:33:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN  13.83
2026-07-06 09:34:00-04:00     NaN  1.2900  NaN    NaN  NaN   NaN  NaN    NaN
...                           ...     ...  ...    ...  ...   ...  ...    ...
2026-07-10 15:55:00-04:00     NaN  1.2850  NaN  6.240  NaN   NaN  NaN    NaN
2026-07-10 15:56:00-04:00     NaN  1.2800  NaN  6.245  NaN   NaN  NaN    NaN
2026-07-10 15:57:00-04:00     NaN  1.2899  NaN  6.260  NaN   NaN  NaN    NaN
2026-07-10 15:58:00-04:00     NaN  1.2800  NaN  6.260  NaN   NaN  NaN    NaN
2026-07-10 15:59:00-04:00  0.4306  1.2850  NaN  6.265  NaN   NaN  NaN  13.56

Price                                                                     \
Ticker                        IIF    IMMR    IMPP INBK IRAB    JRVR KISB
Datetime
2026-07-06 09:30:00-04:00  22.980  6.7175     NaN  NaN  NaN     NaN  NaN
2026-07-06 09:31:00-04:00     NaN  6.7000     NaN  NaN  NaN  4.4409  NaN
2026-07-06 09:32:00-04:00     NaN  6.6900  4.6750  NaN  NaN  4.4999  NaN
2026-07-06 09:33:00-04:00     NaN     NaN  4.6838  NaN  NaN     NaN  NaN
2026-07-06 09:34:00-04:00     NaN     NaN  4.6800  NaN  NaN     NaN  NaN
...                           ...     ...     ...  ...  ...     ...  ...
2026-07-10 15:55:00-04:00     NaN  6.7600     NaN  NaN  NaN  4.5650  NaN
2026-07-10 15:56:00-04:00     NaN  6.7550  4.9750  NaN  NaN  4.5600  NaN
2026-07-10 15:57:00-04:00     NaN  6.7550  4.9750  NaN  NaN  4.5650  NaN
2026-07-10 15:58:00-04:00     NaN  6.7550  4.9900  NaN  NaN  4.5650  NaN
2026-07-10 15:59:00-04:00  22.975  6.7550  5.0000  NaN  NaN  4.5600  NaN

Price                                                                          \
Ticker                      KRMD   KRRO   LFMD    LIEN  LMED MAGH MAMK    MFM
Datetime
2026-07-06 09:30:00-04:00  4.480  13.93  4.905  9.9200  3.87  NaN  NaN  5.610
2026-07-06 09:31:00-04:00    NaN  13.95  4.910     NaN   NaN  NaN  NaN    NaN
2026-07-06 09:32:00-04:00    NaN    NaN  4.968     NaN   NaN  NaN  NaN  5.605
2026-07-06 09:33:00-04:00    NaN    NaN  4.970  9.9600   NaN  NaN  NaN    NaN
2026-07-06 09:34:00-04:00    NaN    NaN    NaN     NaN   NaN  NaN  NaN  5.605
...                          ...    ...    ...     ...   ...  ...  ...    ...
2026-07-10 15:55:00-04:00  4.285  14.49  4.635  9.8150   NaN  NaN  NaN  5.530
2026-07-10 15:56:00-04:00    NaN  14.48  4.620  9.8150   NaN  NaN  NaN  5.530
2026-07-10 15:57:00-04:00  4.280  14.45  4.615  9.8275   NaN  NaN  NaN  5.535
2026-07-10 15:58:00-04:00  4.285  14.50  4.630     NaN   NaN  NaN  NaN  5.535
2026-07-10 15:59:00-04:00  4.280  14.55  4.640  9.8225   NaN  NaN  NaN  5.535

Price                                                                     \
Ticker                     MNTK     NBP   NERV       NKSH    NPV    NUCL
Datetime
2026-07-06 09:30:00-04:00   NaN  2.2272  5.070        NaN  11.56  8.8300
2026-07-06 09:31:00-04:00   NaN  2.1800    NaN  36.009998    NaN  8.7700
2026-07-06 09:32:00-04:00   NaN  2.1400  5.100        NaN    NaN     NaN
2026-07-06 09:33:00-04:00   NaN  2.1000    NaN        NaN    NaN     NaN
2026-07-06 09:34:00-04:00   NaN  2.0809    NaN        NaN    NaN  8.6100
...                         ...     ...    ...        ...    ...     ...
2026-07-10 15:55:00-04:00   NaN  1.9000  4.800  35.970001    NaN  6.8459
2026-07-10 15:56:00-04:00   NaN  1.8950  4.796        NaN    NaN     NaN
2026-07-10 15:57:00-04:00  1.62  1.8950  4.750        NaN  11.38     NaN
2026-07-10 15:58:00-04:00  1.62  1.8950  4.730        NaN  11.41  6.8350
2026-07-10 15:59:00-04:00  1.61  1.8950  4.710  35.810001  11.41  6.8500

Price                                                                \
Ticker                      ONCH   OPBK PALO PEBK       PMTS   PNNT
Datetime
2026-07-06 09:30:00-04:00  10.35  15.23  9.9  NaN  20.379999  3.500
2026-07-06 09:31:00-04:00    NaN  15.22  NaN  NaN        NaN  3.479
2026-07-06 09:32:00-04:00    NaN    NaN  NaN  NaN  20.504999  3.520
2026-07-06 09:33:00-04:00    NaN    NaN  NaN  NaN        NaN  3.510
2026-07-06 09:34:00-04:00    NaN    NaN  NaN  NaN        NaN  3.530
...                          ...    ...  ...  ...        ...    ...
2026-07-10 15:55:00-04:00    NaN  14.87  NaN  NaN        NaN  3.460
2026-07-10 15:56:00-04:00    NaN  14.86  NaN  NaN        NaN  3.465
2026-07-10 15:57:00-04:00    NaN    NaN  NaN  NaN        NaN  3.450
2026-07-10 15:58:00-04:00    NaN  14.86  NaN  NaN  19.495001  3.450
2026-07-10 15:59:00-04:00    NaN  14.88  NaN  NaN  19.495001  3.445

Price                                                                         \
Ticker                          PPIH PSRHF PTAC QNBC     QSI    QTTB    REFI
Datetime
2026-07-06 09:30:00-04:00  25.510000  1.18  NaN  NaN  0.9300  13.150  10.665
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  NaN  0.9287  13.135     NaN
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  NaN  0.9299  13.135  10.670
2026-07-06 09:33:00-04:00  26.270000   NaN  NaN  NaN  0.9299     NaN  10.670
2026-07-06 09:34:00-04:00        NaN  1.15  NaN  NaN  0.9301  13.345  10.670
...                              ...   ...  ...  ...     ...     ...     ...
2026-07-10 15:55:00-04:00  25.190001   NaN  NaN  NaN  0.8904  11.365  10.815
2026-07-10 15:56:00-04:00  25.125000   NaN  NaN  NaN  0.8878  11.310     NaN
2026-07-10 15:57:00-04:00  25.180000   NaN  NaN  NaN  0.8840  11.250  10.820
2026-07-10 15:58:00-04:00        NaN  1.10  NaN  NaN  0.8833  11.270  10.815
2026-07-10 15:59:00-04:00  25.070000   NaN  NaN  NaN  0.8827  11.200  10.820

Price                                                                         \
Ticker                       RNA   RWAY   RXST  SABA    SIDU    SITC    SLNH
Datetime
2026-07-06 09:30:00-04:00  13.60  5.580  5.530  8.30  2.6650  4.5250  1.2250
2026-07-06 09:31:00-04:00    NaN  5.610  5.575   NaN  2.6501  4.5018  1.2250
2026-07-06 09:32:00-04:00    NaN    NaN  5.586   NaN  2.6450  4.4800  1.2499
2026-07-06 09:33:00-04:00    NaN  5.610  5.615   NaN  2.6640  4.4750  1.2450
2026-07-06 09:34:00-04:00    NaN  5.615  5.580   NaN  2.6000  4.4800  1.2500
...                          ...    ...    ...   ...     ...     ...     ...
2026-07-10 15:55:00-04:00    NaN  5.300  4.970  8.18  2.1250  4.2850  1.2650
2026-07-10 15:56:00-04:00  12.38  5.305  4.965  8.18  2.1400  4.2850  1.2600
2026-07-10 15:57:00-04:00  12.46  5.310  4.965   NaN  2.1450  4.2850  1.2650
2026-07-10 15:58:00-04:00  12.45  5.305  4.955  8.18  2.1450  4.2850  1.2600
2026-07-10 15:59:00-04:00  12.49  5.313  4.950  8.18  2.1601  4.2950  1.2670

Price                                                                          \
Ticker                      SMHI       SMTI    SND   SPMC     SPOK       STRS
Datetime
2026-07-06 09:30:00-04:00  7.615  24.549999  4.720  10.15  10.5300  28.184999
2026-07-06 09:31:00-04:00    NaN        NaN  4.680    NaN  10.5800        NaN
2026-07-06 09:32:00-04:00    NaN        NaN    NaN    NaN      NaN        NaN
2026-07-06 09:33:00-04:00    NaN        NaN    NaN    NaN  10.6188  28.184999
2026-07-06 09:34:00-04:00    NaN        NaN    NaN    NaN      NaN        NaN
...                          ...        ...    ...    ...      ...        ...
2026-07-10 15:55:00-04:00  7.810        NaN  4.810    NaN  10.4150  26.010000
2026-07-10 15:56:00-04:00    NaN  23.990000  4.805    NaN  10.4200  26.129999
2026-07-10 15:57:00-04:00    NaN  23.879999  4.805    NaN  10.4150  26.049999
2026-07-10 15:58:00-04:00  7.810  23.860001    NaN    NaN  10.3999  26.100000
2026-07-10 15:59:00-04:00  7.800  23.670000  4.805    NaN  10.4050  26.080000

Price                                                                 \
Ticker                    SUGRF SVCC   TDAC TETOF TGMPF    TSI TSNDF
Datetime
2026-07-06 09:30:00-04:00   NaN  NaN  10.72   NaN   NaN  4.490   NaN
2026-07-06 09:31:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:32:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:33:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
2026-07-06 09:34:00-04:00   NaN  NaN    NaN   NaN   NaN    NaN   NaN
...                         ...  ...    ...   ...   ...    ...   ...
2026-07-10 15:55:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:56:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:57:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475   NaN
2026-07-10 15:58:00-04:00   NaN  NaN    NaN   NaN   NaN  4.475  0.57
2026-07-10 15:59:00-04:00   NaN  NaN    NaN   NaN   NaN  4.470  0.57

Price                                                                Close  \
Ticker                          UTMD     VLN   VYGR   WALD WEWA       AIFU
Datetime
2026-07-06 09:30:00-04:00        NaN  2.1450  3.790  1.680  NaN        NaN
2026-07-06 09:31:00-04:00        NaN  2.1469  3.805  1.690  NaN        NaN
2026-07-06 09:32:00-04:00        NaN  2.1499  3.805    NaN  NaN        NaN
2026-07-06 09:33:00-04:00        NaN  2.1201  3.811    NaN  NaN        NaN
2026-07-06 09:34:00-04:00        NaN  2.1400  3.806    NaN  NaN        NaN
...                              ...     ...    ...    ...  ...        ...
2026-07-10 15:55:00-04:00        NaN  2.0650  3.455  1.735  NaN        NaN
2026-07-10 15:56:00-04:00        NaN  2.0650  3.455    NaN  NaN        NaN
2026-07-10 15:57:00-04:00        NaN  2.0650  3.450  1.730  NaN  36.990002
2026-07-10 15:58:00-04:00        NaN  2.0650  3.453  1.730  NaN        NaN
2026-07-10 15:59:00-04:00  67.889999  2.0750  3.445  1.745  NaN        NaN

Price                                                                   \
Ticker                      AIRO       ALOT   ALTG   ANIK  AOMR   ASUR
Datetime
2026-07-06 09:30:00-04:00  7.860  28.525000  6.210    NaN  9.03  8.220
2026-07-06 09:31:00-04:00  7.830        NaN  6.070    NaN   NaN  8.050
2026-07-06 09:32:00-04:00  7.880  28.530001  6.080    NaN   NaN  8.275
2026-07-06 09:33:00-04:00    NaN        NaN    NaN    NaN   NaN    NaN
2026-07-06 09:34:00-04:00  7.775        NaN    NaN    NaN   NaN    NaN
...                          ...        ...    ...    ...   ...    ...
2026-07-10 15:55:00-04:00  6.305  28.510000  6.590    NaN  9.04  7.810
2026-07-10 15:56:00-04:00  6.305        NaN  6.590    NaN   NaN  7.850
2026-07-10 15:57:00-04:00  6.300  28.510000  6.585  15.59  9.06    NaN
2026-07-10 15:58:00-04:00  6.300  28.510000  6.580    NaN  9.03  7.830
2026-07-10 15:59:00-04:00  6.275  28.510000  6.620  15.59  9.03  7.820

Price                                                                 \
Ticker                          BDSX BGIN BIII  BLRK BXSY  CAMP CCAQ
Datetime
2026-07-06 09:30:00-04:00  21.809999  NaN  NaN  9.99  NaN  4.42  NaN
2026-07-06 09:31:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:32:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:33:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-06 09:34:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
...                              ...  ...  ...   ...  ...   ...  ...
2026-07-10 15:55:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:56:00-04:00        NaN  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:57:00-04:00  21.530001  NaN  NaN   NaN  NaN   NaN  NaN
2026-07-10 15:58:00-04:00  21.260000  NaN  NaN   NaN  NaN  4.35  NaN
2026-07-10 15:59:00-04:00  21.309999  NaN  NaN   NaN  NaN   NaN  NaN

Price                                                                     \
Ticker                          CMTV CRAC    CRNT CTAA       CZWI   DWSN
Datetime
2026-07-06 09:30:00-04:00  39.500000  NaN  2.4100  NaN  23.754999  5.890
2026-07-06 09:31:00-04:00  38.000000  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:32:00-04:00  40.200001  NaN  2.4100  NaN        NaN    NaN
2026-07-06 09:33:00-04:00  39.500000  NaN  2.4310  NaN        NaN    NaN
2026-07-06 09:34:00-04:00        NaN  NaN  2.4399  NaN        NaN  5.890
...                              ...  ...     ...  ...        ...    ...
2026-07-10 15:55:00-04:00        NaN  NaN     NaN  NaN  23.065001  7.525
2026-07-10 15:56:00-04:00        NaN  NaN  2.3450  NaN  23.059999  7.470
2026-07-10 15:57:00-04:00        NaN  NaN  2.3450  NaN  23.049999  7.540
2026-07-10 15:58:00-04:00  38.639999  NaN  2.3500  NaN        NaN  7.570
2026-07-10 15:59:00-04:00        NaN  NaN  2.3550  NaN  23.070000  7.590

Price                                                                     \
Ticker                          EFSI   EGG EGHA   EVTL       FCAP     FF
Datetime
2026-07-06 09:30:00-04:00  41.904999  7.19  NaN  1.940  65.750000  4.720
2026-07-06 09:31:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:32:00-04:00        NaN   NaN  NaN  1.935        NaN  4.715
2026-07-06 09:33:00-04:00        NaN   NaN  NaN  1.940        NaN  4.715
2026-07-06 09:34:00-04:00        NaN   NaN  NaN  1.920        NaN  4.715
...                              ...   ...  ...    ...        ...    ...
2026-07-10 15:55:00-04:00  40.560001   NaN  NaN  1.665        NaN  4.665
2026-07-10 15:56:00-04:00        NaN   NaN  NaN  1.670        NaN  4.665
2026-07-10 15:57:00-04:00  40.560001   NaN  NaN  1.670        NaN  4.660
2026-07-10 15:58:00-04:00  40.509998   NaN  NaN  1.665        NaN  4.660
2026-07-10 15:59:00-04:00  40.509998   NaN  NaN  1.660  61.950001  4.640

Price                                                                       \
Ticker                      FJET        FOA FOCL FOTB    GCTS GDEV    GENC
Datetime
2026-07-06 09:30:00-04:00  5.030  27.250000  NaN  NaN  2.6865  NaN     NaN
2026-07-06 09:31:00-04:00  4.950        NaN  NaN  NaN  2.6700  NaN     NaN
2026-07-06 09:32:00-04:00  4.930        NaN  NaN  NaN     NaN  NaN     NaN
2026-07-06 09:33:00-04:00  4.930        NaN  NaN  NaN  2.6550  NaN     NaN
2026-07-06 09:34:00-04:00  4.945        NaN  NaN  NaN  2.6551  NaN     NaN
...                          ...        ...  ...  ...     ...  ...     ...
2026-07-10 15:55:00-04:00  4.425  25.530001  NaN  NaN  2.4503  NaN     NaN
2026-07-10 15:56:00-04:00  4.450        NaN  NaN  NaN  2.4650  NaN     NaN
2026-07-10 15:57:00-04:00  4.430  25.490000  NaN  NaN  2.4650  NaN  15.485
2026-07-10 15:58:00-04:00  4.425  25.625000  NaN  NaN  2.4650  NaN  15.480
2026-07-10 15:59:00-04:00  4.440  25.830000  NaN  NaN  2.4600  NaN  15.535

Price                                                                         \
Ticker                      GLATF    GORO GSHR    GTE HAVA ICTSF IDAC    IDE
Datetime
2026-07-06 09:30:00-04:00  0.4723  1.2850  NaN  5.910  NaN   NaN  NaN  13.82
2026-07-06 09:31:00-04:00     NaN  1.2850  NaN  5.915  NaN   NaN  NaN    NaN
2026-07-06 09:32:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN    NaN
2026-07-06 09:33:00-04:00     NaN  1.2950  NaN    NaN  NaN   NaN  NaN  13.83

In [81]:
df1 = df1.stack(0).rename_axis(['date', 'ticker']).reset_index(1).reset_index()
df1

Ticker,date,ticker,AIFU,AIRO,ALOT,ALTG,ANIK,AOMR,ASUR,BDSX,BGIN,BIII,BLRK,BXSY,CAMP,CCAQ,CMTV,CRAC,CRNT,CTAA,CZWI,DWSN,EFSI,EGG,EGHA,EVTL,FCAP,FF,FJET,FOA,FOCL,FOTB,GCTS,GDEV,GENC,GLATF,GORO,GSHR,GTE,HAVA,ICTSF,IDAC,IDE,IIF,IMMR,IMPP,INBK,IRAB,JRVR,KISB,KRMD,KRRO,LFMD,LIEN,LMED,MAGH,MAMK,MFM,MNTK,NBP,NERV,NKSH,NPV,NUCL,ONCH,OPBK,PALO,PEBK,PMTS,PNNT,PPIH,PSRHF,PTAC,QNBC,QSI,QTTB,REFI,RNA,RWAY,RXST,SABA,SIDU,SITC,SLNH,SMHI,SMTI,SND,SPMC,SPOK,STRS,SUGRF,SVCC,TDAC,TETOF,TGMPF,TSI,TSNDF,UTMD,VLN,VYGR,WALD,WEWA
0,2026-07-06 09:30:00-04:00,Adj Close,NaN,7.860,28.525000,6.210,NaN,9.030,8.22,21.809999,NaN,NaN,9.99,NaN,4.42,NaN,39.500000,NaN,2.410,NaN,23.754999,5.89,41.904999,7.19,NaN,1.9400,65.750000,4.720,5.030,27.25,NaN,NaN,2.6865,NaN,NaN,0.47230,1.285,NaN,5.91,NaN,NaN,NaN,13.82,22.980000,6.7175,NaN,NaN,NaN,NaN,NaN,4.48,13.930,4.9050,9.9200,3.87,NaN,NaN,5.610,NaN,2.2272,5.070,NaN,11.56,8.830,10.35,15.23,9.9,NaN,20.379999,3.500,25.51,1.18,NaN,NaN,0.9300,13.15,10.665,13.60,5.580,5.53,8.30,2.6650,4.525,1.225,7.615,24.549999,4.720,10.15,10.5300,28.184999,NaN,NaN,10.72,NaN,NaN,4.4900,NaN,NaN,2.145,3.79,1.680,NaN
1,2026-07-06 09:30:00-04:00,Close,NaN,7.860,28.525000,6.210,NaN,9.030,8.22,21.809999,NaN,NaN,9.99,NaN,4.42,NaN,39.500000,NaN,2.410,NaN,23.754999,5.89,41.904999,7.19,NaN,1.9400,65.750000,4.720,5.030,27.25,NaN,NaN,2.6865,NaN,NaN,0.47230,1.285,NaN,5.91,NaN,NaN,NaN,13.82,22.980000,6.7175,NaN,NaN,NaN,NaN,NaN,4.48,13.930,4.9050,9.9200,3.87,NaN,NaN,5.610,NaN,2.2272,5.070,NaN,11.56,8.830,10.35,15.23,9.9,NaN,20.379999,3.500,25.51,1.18,NaN,NaN,0.9300,13.15,10.665,13.60,5.580,5.53,8.30,2.6650,4.525,1.225,7.615,24.549999,4.720,10.15,10.5300,28.184999,NaN,NaN,10.72,NaN,NaN,4.4900,NaN,NaN,2.145,3.79,1.680,NaN
2,2026-07-06 09:30:00-04:00,Dividends,NaN,0.000,0.000000,0.000,NaN,0.000,0.00,0.000000,NaN,NaN,0.00,NaN,0.00,NaN,0.000000,NaN,0.000,NaN,0.000000,0.00,0.000000,0.00,NaN,0.0000,0.000000,0.000,0.000,0.00,NaN,NaN,0.0000,NaN,NaN,0.00000,0.000,NaN,0.00,NaN,NaN,NaN,0.00,0.000000,0.0000,NaN,NaN,NaN,NaN,NaN,0.00,0.000,0.0000,0.0000,0.00,NaN,NaN,0.000,NaN,0.0000,0.000,NaN,0.00,0.000,0.00,0.00,0.0,NaN,0.000000,0.000,0.00,0.00,NaN,NaN,0.0000,0.00,0.000,0.00,0.000,0.00,0.00,0.0000,0.000,0.000,0.000,0.000000,0.000,0.00,0.0000,0.000000,NaN,NaN,0.00,NaN,NaN,0.0000,NaN,NaN,0.000,0.00,0.000,NaN
3,2026-07-06 09:30:00-04:00,High,NaN,7.860,28.559999,6.210,NaN,9.065,8.22,21.809999,NaN,NaN,9.99,NaN,4.42,NaN,39.669998,NaN,2.460,NaN,23.754999,5.99,41.904999,7.19,NaN,1.9500,65.750000,4.720,5.040,27.25,NaN,NaN,2.7000,NaN,NaN,0.47230,1.290,NaN,5.91,NaN,NaN,NaN,13.82,22.980000,6.7300,NaN,NaN,NaN,NaN,NaN,4.49,13.930,4.9050,9.9200,3.87,NaN,NaN,5.610,NaN,2.2600,5.070,NaN,11.56,8.830,10.35,15.23,9.9,NaN,21.378000,3.505,25.51,1.22,NaN,NaN,0.9300,13.15,10.665,13.61,5.580,5.60,8.30,2.6699,4.525,1.230,7.615,24.549999,4.730,10.15,10.6999,28.184999,NaN,NaN,10.72,NaN,NaN,4.4900,NaN,NaN,2.150,3.80,1.680,NaN
4,2026-07-06 09:30:00-04:00,Low,NaN,7.760,28.500000,6.160,NaN,9.010,8.22,21.809999,NaN,NaN,9.99,NaN,4.42,NaN,39.500000,NaN,2.370,NaN,23.754999,5.89,40.900002,7.19,NaN,1.8984,65.750000,4.690,4.850,27.25,NaN,NaN,2.6500,NaN,NaN,0.47230,1.275,NaN,5.91,NaN,NaN,NaN,13.82,22.980000,6.7175,NaN,NaN,NaN,NaN,NaN,4.48,13.930,4.8101,9.9200,3.85,NaN,NaN,5.610,NaN,2.2272,5.070,NaN,11.56,8.820,10.35,15.23,9.9,NaN,20.379999,3.470,25.51,1.16,NaN,NaN,0.9280,13.09,10.640,13.56,5.490,5.52,8.26,2.6400,4.495,1.220,7.590,24.549999,4.670,10.15,10.4900,27.500000,NaN,NaN,10.72,NaN,NaN,4.4900,NaN,NaN,2.100,3.79,1.660,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15595,2026-07-10 15:59:00-04:00,High,NaN,6.305,28.510000,6.620,15.615,9.030,7.84,21.635000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.365,NaN,23.080000,7.63,40.509998,NaN,NaN,1.6700,61.950001,4.655,4.440,25.83,NaN,NaN,2.4700,NaN,15.565,0.43205,1.290,NaN,6.28,NaN,NaN,NaN,13.56,22.975000,6.7550,5.000,NaN,NaN,4.565,NaN,4.28,14.550,4.6400,9.8225,NaN,NaN,NaN,5.535,1.625,1.9000,4.735,35.950001,11.41,6.850,NaN,14.88,NaN,NaN,19.495001,3.455,25.17,NaN,NaN,NaN,0.8898,11.37,10.820,12.49,5.325,4.96,8.19,2.1700,4.295,1.270,7.830,23.830000,4.810,NaN,10.4100,26.160000,NaN,NaN,NaN,NaN,NaN,4.4788,0.57,67.889999,2.080,3.45,1.745,NaN
15596,2026-07-10 15:59:00-04:00,Low,NaN,6.270,28.510000,6.575,15.560,9.010,7.82,21.309999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.355,NaN,23.059999,7.54,40.509998,NaN,NaN,1.6600,61.950001,4.630,4.420,25.77,NaN,NaN,2.4600,NaN,15.440,0.43050,1.285,NaN,6.25,NaN,NaN,NaN,13.56,22.959999,6.7500,4.975,NaN,NaN,4.560,NaN,4.27,14.425,4.6300,9.8150,NaN,NaN,NaN,5.535,1.610,1.8900,4.710,35.810001,11.40,6.825,NaN,14.87,NaN,NaN,19.405001,3.440,25.07,NaN,NaN,NaN,0.8827,11.15,10.810,12.44,5.310,4.95,8.18,2.1400,4.280,1.260,7.760,23.670000,4.800,NaN,10.4000,26.049999,NaN,NaN,NaN,NaN,NaN,4.4700,0.57,67.889999,2.060,3.44,1.730,NaN
15597,2026-07-10 15:59:00-04:00,Open,NaN,6.305,28.510000,6.575,15.615,9.025,7.84,21.635000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.360,NaN,23.059999,7.55,40.509998,NaN,NaN,1.6650,61.950001,4.655,4.425,25.77,NaN,NaN,2.4650,NaN,15.440,0.43205,1.285,NaN,6.26,NaN,NaN,NaN,13.56,22.959999,6.7550,4.980,NaN,NaN,4.560,NaN,4.28,14.480,4.6350,9.8150,NaN,NaN,NaN,5.535,1.620,1.9000,4.730,35.950001,11.40,6.830,NaN,14.87,NaN,NaN,19.415001,3.450,25.17,NaN,NaN,NaN,0.8838,11.16,10.810,12.45,5.310,4.96,8.18,2.1450,4.280,1.260,7.790,23.830000,4.805,NaN,10.4000,26.094999,NaN,NaN,NaN,NaN,NaN,4.4750,0.57,67.889999,2.060,3.45,1.735,NaN
15598,2026-07-10 15:59:00-04:00,Stock Splits,NaN,0.000,0.000000,0.000,0.000,0.000,0.00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,NaN,0.000000,0.00,0.000000,NaN,NaN,0.0000,0.000000,0.000,0.000,0.00,NaN,NaN,0.0000,NaN,0.000,0.00000,0.000,NaN,0.00,NaN,NaN,NaN,0.00,0.000000,0.0000,0.000,NaN,NaN,0.000,NaN,0.00,0.000,0.0000,0.0000,NaN,NaN,NaN,0.000,0.000,0.0000,0.000,0.000000,0.00,0.000,NaN,0.00,NaN,NaN,0.000000,0.000,0.00,NaN,NaN,NaN,0.0000,0.00,0.000,0.00,0.000,0.00,0.00,0.0000,0.000,0.000,0.000,0.000000,0.000,NaN,0.0000,0.000000,NaN,NaN,NaN,NaN,NaN,0.0000,0.00,0.000000,0.000,0.00,0.000,NaN
15599,2026-07-10 15:59:00-04:00,Volume,NaN,21353.000,2384.000000,12108.000,3894.000,3593.000,5544.00,901.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13243.000,NaN,3109.000000,7943.00,819.000000,NaN,NaN,32570.0000,161.000000,11812.000,7038.000,2022.00,NaN,NaN,10705.0000,NaN,4162.000,18900.00000,16621.000,NaN,4890.00,NaN,NaN,NaN,2150.00,327.000000,9699.0000,7453.000,NaN,NaN,5219.000,NaN,3368.00,11841.000,6566.0000,650.0000,NaN,NaN,NaN,538.000,5094.000,6247.0000,6074.000,1408.000000,904.00,1692.000,NaN,1032.00,NaN,NaN,1133.000000,24600.000,2917.00,NaN,NaN,NaN,24836.0000,41186.00,3066.000,8077.00,20964.000,12026.00,2114.00,460780.0000,39745.000,66200.000,10768.000,2225.000000,5302.000,NaN,7685.0000,29040.000000,NaN,NaN,NaN,NaN,NaN,1660.0000,2000.00,138.000000,22927.000,16222.00,11907.000,NaN

In [82]:
long

                             date         field symbol  value
0       2026-07-06 09:30:00-04:00     Adj Close   GSHR    NaN
1       2026-07-06 09:30:00-04:00         Close   GSHR    NaN
2       2026-07-06 09:30:00-04:00     Dividends   GSHR    NaN
3       2026-07-06 09:30:00-04:00          High   GSHR    NaN
4       2026-07-06 09:30:00-04:00           Low   GSHR    NaN
...                           ...           ...    ...    ...
1559995 2026-07-10 15:59:00-04:00          High   WEWA    NaN
1559996 2026-07-10 15:59:00-04:00           Low   WEWA    NaN
1559997 2026-07-10 15:59:00-04:00          Open   WEWA    NaN
1559998 2026-07-10 15:59:00-04:00  Stock Splits   WEWA    NaN
1559999 2026-07-10 15:59:00-04:00        Volume   WEWA    NaN

[1560000 rows x 4 columns]

In [83]:
long = (
    df1.melt(id_vars=["date", "ticker"], var_name="symbol", value_name="value")
       .rename(columns={"ticker": "field"})   # Close/High/Low/... = field, not ticker
)
long
out = long.pivot_table(index=["date", "symbol"], columns="field", values="value").reset_index()
out

field,date,symbol,Adj Close,Close,Dividends,High,Low,Open,Stock Splits,Volume
0,2026-07-06 09:30:00-04:00,AIRO,7.860000,7.860000,0.0,7.860000,7.760000,7.760000,0.0,10939.0
1,2026-07-06 09:30:00-04:00,ALOT,28.525000,28.525000,0.0,28.559999,28.500000,28.549999,0.0,4977.0
2,2026-07-06 09:30:00-04:00,ALTG,6.210000,6.210000,0.0,6.210000,6.160000,6.160000,0.0,0.0
3,2026-07-06 09:30:00-04:00,AOMR,9.030000,9.030000,0.0,9.065000,9.010000,9.010000,0.0,1356.0
4,2026-07-06 09:30:00-04:00,ASUR,8.220000,8.220000,0.0,8.220000,8.220000,8.220000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
49030,2026-07-10 15:59:00-04:00,ANIK,15.590000,15.590000,0.0,15.615000,15.560000,15.615000,0.0,3894.0
49031,2026-07-10 15:59:00-04:00,MNTK,1.610000,1.610000,0.0,1.625000,1.610000,1.620000,0.0,5094.0
49032,2026-07-10 15:59:00-04:00,GENC,15.535000,15.535000,0.0,15.565000,15.440000,15.440000,0.0,4162.0
49033,2026-07-10 15:59:00-04:00,TSNDF,0.570000,0.570000,0.0,0.570000,0.570000,0.570000,0.0,2000.0
49034,2026-07-10 15:59:00-04:00,UTMD,67.889999,67.889999,0.0,67.889999,67.889999,67.889999,0.0,138.0

#### Note on `Adj Close` and interval choice

`Adj Close` behaviour depends on `auto_adjust`, not the interval:

- `auto_adjust=True` (yfinance default) folds split/div adjustment **into** `Close` and emits **no**
  separate `Adj Close` column → it shows as all-NaN and `pivot_table(dropna=True)` drops it.
- `auto_adjust=False` keeps raw `Close` **and** a separate `Adj Close`.

For **intraday** (`1m`, `1h`) `Adj Close == Close` — no split/dividend applies mid-session, so the
column is redundant. Adjustment only matters across **days**, i.e. `1d`.

| Interval | history limit | `auto_adjust` | Adj Close | use |
|----------|--------------|---------------|-----------|-----|
| `1m` | last ~8 days | `True` | drop (redundant) | live feed → `market.ohlcv.1m` |
| `1h` | last ~730 days | `True` | drop (redundant) | medium-history backfill |
| `1d` | full history | `False` | **keep** (real adjustment) | long-horizon / return features |

Rule of thumb: **`Adj Close` only for `1d`.** Select columns explicitly rather than leaning on
`dropna`, so the schema stays stable when a field is sparse.

In [84]:
out.columns

Index(['date', 'symbol', 'Adj Close', 'Close', 'Dividends', 'High', 'Low',
       'Open', 'Stock Splits', 'Volume'],
      dtype='str', name='field')

In [77]:
long.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 1560000 entries, 0 to 1559999
Data columns (total 4 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   date    1560000 non-null  datetime64[s, America/New_York]
 1   field   1560000 non-null  str
 2   symbol  1560000 non-null  str
 3   value   343245 non-null   float64
dtypes: datetime64[s, America/New_York](1), float64(1), str(2)
memory usage: 185.1 MB

In [14]:
Ticker('CXAIW').history(period="1d", start="2026-07-11")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-07-10 00:00:00-04:00,0.0998,0.0594,0.0553,0.0565,10888,0.0,0.0